version: 2
updates:
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "cron"
      cronjob: "30 9 * * *"
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "cron"
      cronjob: "4 9 * * *"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "cron"
      cronjob: "44 9 * * *"
