apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nycmesh-building.fullname" . }}
type: Opaque
data:
  MESHDB_API_KEY: {{ .Values.building.meshdb_api_key | b64enc | quote }}
  UISP_API_KEY: {{ .Values.building.uisp_api_key | b64enc | quote }}
  STRIPE_API_KEY: {{ .Values.building.stripe_api_key | b64enc | quote }}
  NINJA_API_KEY: {{ .Values.building.ninja_api_key | b64enc | quote }}
  OIDC_RP_CLIENT_ID: {{ .Values.building.oidc_rp_client_id | b64enc | quote }}
  OIDC_RP_CLIENT_SECRET: {{ .Values.building.oidc_rp_client_secret | b64enc | quote }}
