apiVersion: v1
kind: Service
metadata:
  name: {{ include "nycmesh-building.fullname" . }}
  labels:
    {{- include "nycmesh-building.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: 30001
      protocol: TCP
      name: http
  selector:
    {{- include "nycmesh-building.selectorLabels" . | nindent 4 }}
